sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "7"

# To use electron-mocha
addons:
  apt:
    packages:
      - xvfb
before_install:
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - export DISPLAY=':99.0'
